### ISSUE TITLE
Webpack error on Windows

### ISSUE THREAD

**Issue by OkancanCosar** [mmazzarolo/react-native-universal-monorepo#12]
Hello, first of all thank you very much for this guide. It was really good. But I'm stuck at one place. After completing the mobile and web installations, I get an error when I start it with "yarn web:start".
I've created a repository and added the error screenshot to readme.md so you can test the faulty code.

https://github.com/OkancanCosar/react-personal-monorepo

Thank you for your help :)

**Comment by mmazzarolo** [comment]
Hey @OkancanCosar ! Thanks for reporting :)
I assume you're on Windows, right? 
At a first glance, it looks like the issue is caused by [`getWebpackTools`](https://github.com/mmazzarolo/react-native-monorepo-tools/blob/621c3e44c34999b9333ba84d3584c46849f0020b/src/get-webpack-tools.js#L50) not setting correctly the slashes? I don't have a windows machine around, but could you try changing the `workspace` (in `packages/web/node_modules/react-native-monorepo-tools/src/get-webpack-tools.js`) variable referenced in that line of code to use Windows-compatible slashes and then run `yarn web:start` again to see if it solves the issue?

**Comment by mmazzarolo** [comment]
@OkancanCosar I've found the issue :) 
It's actually a mistake I've made in the tutorial. 
Could you please rename `packages/app/src/app.js` to `packages/app/src/index.js`? 
It should fix the issue. You should also add a "logo" image to `packages/app/src/logo.png`. 
Thanks for reporting, I'll update the blog post 👍

**Comment by OkancanCosar** [comment]
oh I think Im blind. Thank you for everything. works well

**Comment by OkancanCosar** [comment]
i was so disturb to you but when running android, getting this.

```
error: Error: Unable to resolve module react from C:\Users\ENFOTEK25\Desktop\my-app\packages\app\src\index.js: react could not be found within the project or in these directories:
  ..\app\node_modules
  ..\..\node_modules  
```
react couldnt found. actually react inside ../../../node_modules right?
